import type { Metadata } from 'next'

import CompanyNavbar from '@/components/CompanyNavbar'
export const metadata: Metadata = {
	title: 'Placement Portal',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<section>
            <header>
                <CompanyNavbar />
            </header>
            {children}
        </section>
	)
}
